# Default initial positions for elfin10_l's ros2_control fake system

initial_positions:
  elfin_joint1: 0
  elfin_joint2: 0
  elfin_joint3: 0
  elfin_joint4: 0
  elfin_joint5: 0
  elfin_joint6: 0
  finger_joint: 0
  left_inner_finger_joint: 0
  left_inner_knuckle_joint: 0
  right_inner_finger_joint: 0
  right_inner_knuckle_joint: 0
  right_outer_knuckle_joint: 0